### ISSUE TITLE
Contacts disappear on Mailchimp

### ISSUE THREAD

**Issue by pgervaix** [sciencegalleryderek/com.sciencegallery.mailchimp#17]
Hi,
I have a big problem with the sync script,
when the scheduled job "Call Mailchimp.SyncSmartGroups API" ran, the jobs , he deleted all my contacts on Mailchimp
I dont use smart group within mailchimp,
can i disabled the job?
thanks in advance

**Comment by sciencegalleryderek** [comment]
Hi @pgervaix 

It looks like the script was trying to sync all groups instead of just smart groups leading to all contacts in the regular groups being deleted from mamilchimp. I think I have it fixed in the v1.3 branch I've created - if you can try this and let me know if you're still seeing the issue?
